IF EXISTS (SELECT * FROM DBO.SYSOBJECTS WHERE NAME='sp_ISO_InsertSoTayGiaoVien')
BEGIN
	DROP PROC sp_ISO_InsertSoTayGiaoVien
END
GO
CREATE PROC sp_ISO_InsertSoTayGiaoVien
	@Ma_KHGD INT,
	@KQ INT OUTPUT
AS
BEGIN
	SET @KQ=-1
	IF NOT EXISTS (SELECT * FROM SoTayGiaoVien WHERE Ma_KHGD=@Ma_KHGD)
	BEGIN
		INSERT INTO SoTayGiaoVien(Ma_KHGD,Tinh_trang,Ngay_cap_nhat_cuoi) VALUES (@Ma_KHGD,'0',GETDATE())
		SELECT @KQ=MAX(ID) FROM SoTayGiaoVien
	END
	ELSE
	BEGIN
		SELECT @KQ=ID FROM SoTayGiaoVien WHERE Ma_KHGD=@Ma_KHGD
	END
END