IF EXISTS (SELECT * FROM DBO.SYSOBJECTS WHERE NAME='sp_UpdateSttChiTietKHGD')
BEGIN
	DROP PROC sp_UpdateSttChiTietKHGD
END
GO
CREATE PROC sp_UpdateSttChiTietKHGD
AS
BEGIN
	DECLARE @C CURSOR
	DECLARE @C1 CURSOR
	DECLARE @Ma_KHGD INT
	DECLARE @Ma_CTKHGD INT
	DECLARE @STT INT
	SET @C = CURSOR FOR SELECT ID FROM KEHOACHGIANGDAY
	OPEN @C
	FETCH NEXT FROM @C INTO @Ma_KHGD
	WHILE @@FETCH_STATUS = 0
	BEGIN
		SET @STT=1
		SET @C1 = CURSOR FOR SELECT ID FROM CHITIETKHGD WHERE MA_KE_HOACH_GIANG_DAY=@Ma_KHGD ORDER BY Ngay_BD ASC
		OPEN @C1
		FETCH NEXT FROM @C1 INTO @Ma_CTKHGD
		WHILE @@FETCH_STATUS = 0
		BEGIN
			UPDATE CHITIETKHGD SET USER1=@STT WHERE ID=@Ma_CTKHGD
			SET @STT=@STT+1
			FETCH NEXT FROM @C1 INTO @Ma_CTKHGD
		END
		CLOSE @C1
		DEALLOCATE @C1
		FETCH NEXT FROM @C INTO @Ma_KHGD
	END
	CLOSE @C
	DEALLOCATE @C
END