IF EXISTS (SELECT * FROM DBO.SYSOBJECTS WHERE NAME='sp_NhanSu_InsertChungChiBangCapKhac')
BEGIN
	DROP PROC sp_NhanSu_InsertChungChiBangCapKhac
END
GO
CREATE PROC sp_NhanSu_InsertChungChiBangCapKhac
@Ten NVARCHAR(1000),
@Loai INT,
@Do_uu_tien INT,
@KQ INT OUTPUT
AS
BEGIN
	SET @KQ = -1
	IF NOT EXISTS (SELECT * FROM CHUNGCHIBANGCAPKHAC WHERE Ten=@Ten)
	BEGIN
		DECLARE @C CURSOR
		DECLARE @ID INT
		DECLARE @DUT INT
		IF EXISTS (SELECT * FROM CHUNGCHIBANGCAPKHAC WHERE Loai=@Loai AND Do_uu_tien=@Do_uu_tien+1)
		BEGIN
			SET @C = CURSOR FOR SELECT ID,Do_uu_tien FROM CHUNGCHIBANGCAPKHAC WHERE Loai=@Loai AND Do_uu_tien>@Do_uu_tien
			OPEN @C
			FETCH NEXT FROM @C INTO @ID,@DUT
			WHILE @@FETCH_STATUS = 0
			BEGIN
				UPDATE CHUNGCHIBANGCAPKHAC SET Do_uu_tien=@DUT+1 WHERE ID=@ID
				FETCH NEXT FROM @C INTO @ID,@DUT
			END
			CLOSE @C
			DEALLOCATE @C
		END
		INSERT INTO CHUNGCHIBANGCAPKHAC(Ten,Loai,Do_uu_tien,Ngay_cap_nhat_cuoi)
		VALUES (@Ten,@Loai,@Do_uu_tien+1,GETDATE())
		SELECT @KQ=MAX(ID) FROM CHUNGCHIBANGCAPKHAC
		SET @C = CURSOR FOR SELECT ID FROM CHUNGCHIBANGCAPKHAC WHERE Loai=@Loai ORDER BY Do_uu_tien
		SET @DUT = 0
		OPEN @C
		FETCH NEXT FROM @C INTO @ID
		WHILE @@FETCH_STATUS = 0
		BEGIN
			UPDATE CHUNGCHIBANGCAPKHAC SET Do_uu_tien=@DUT WHERE ID=@ID
			SET @DUT = @DUT+1
			FETCH NEXT FROM @C INTO @ID
		END
		CLOSE @C
		DEALLOCATE @C
		
	END	
END