/*
NGUOI VIET: QCHUONG
NGAY VIET: 02/12/2011
MUC DICH: LAY DIEM TONG DIEM (DIEM TB) TUNG MON HOC CUA 1 SINH VIEN 
THAM SO VAO:
-MASV(KHONG PHAI TEN DANG NHAP).
-HOCKI: NHAP VAO SO HOC KI (VD: 1|2|3) TUONG DUONG VOI: 1<=>HOC KI 1 DUA VAO COT USER1 TRONG TABLE THOIKHOABIEU 
Luu y: insert du lieu mau va cap nhat lai du lieu de co the print theo SP_QLSV_GETTHONGTINCANHANSVBYMATHANHVIEN và SP_QLSV_GETDIEMSVTHEOHOCKI
insert và cap nhat lai du lieu cuoi file SP_QLSV_GETTHONGTINCANHANSVBYMATHANHVIEN
*/
IF EXISTS (SELECT * FROM SYSOBJECTS WHERE NAME = 'SP_QLSV_GETDIEMSVTHEOHOCKI')
BEGIN
	DROP PROC SP_QLSV_GETDIEMSVTHEOHOCKI
END
GO
CREATE PROC SP_QLSV_GETDIEMSVTHEOHOCKI
@MASV INT,
@HOCKI INT
AS
BEGIN
	DECLARE @QUERY NVARCHAR(2000)
	DECLARE @HK INT
	DECLARE @MALOP INT
	DECLARE @TENDN VARCHAR(100)
	SET @HK = NULL
	SET @TENDN = (SELECT TEN_DN FROM THANHVIEN WHERE ID = @MASV)
	SET @MALOP = (SELECT MA_LOP_HOC FROM CHITIETTHANHVIEN WHERE TEN_DANG_NHAP = @TENDN)
	SET @HK = (SELECT ID FROM THOIKHOABIEU WHERE MA_LOP = @MALOP AND UPPER(USER1) LIKE N'%HỌC KÌ '+CAST(@HOCKI AS VARCHAR)+'%')	
--	PRINT 'TENDN : '+CAST(@TENDN AS VARCHAR)
--	PRINT 'MALOP : '+CAST(@MALOP AS VARCHAR)
--	PRINT 'HOCKI : '+CAST(@HK AS VARCHAR)
	
	SELECT DISTINCT /*T1.ID AS [MASV],T1.TEN_DN,C.MA_LOP_HOC,M.ID,M.MA_TKB,M.MA_MON_HOC,M.TEN_MON_HOC,*/MH.TEN_MON_HOC,D.DIEM_TRUNG_BINH 
	FROM THANHVIEN T1 INNER JOIN CHITIETTHANHVIEN C ON T1.TEN_DN = C.TEN_DANG_NHAP
	INNER JOIN THOIKHOABIEU T2 ON C.MA_LOP_HOC = T2.MA_LOP
	INNER JOIN MONHOCTKB M ON T2.ID = M.MA_TKB 
	INNER JOIN DANGKYMONHOC D ON D.MA_MON_HOC_TKB = M.ID
	INNER JOIN MONHOC MH ON MH.ID = M.MA_MON_HOC
	WHERE D.MA_HOC_VIEN = CAST(@MASV AS VARCHAR(10)) AND D.MA_HOC_VIEN = T1.ID 
									AND M.MA_TKB = CAST(@HK AS VARCHAR(10))
		--PRINT @QUERY
END

--DECLARE @A INT
--SET @A = 123
--DECLARE @Q NVARCHAR(2000)
--SET @Q = 'SELECT '+CAST(123123 AS VARCHAR)
--PRINT @Q 

/*
EXEC SP_QLSV_GETDIEMSVTHEOHOCKI 56,2

maThanhVien dùng để test: 56,106,187
SELECT * FROM THANHVIEN WHERE ID = 106
SELECT * FROM CHITIETTHANHVIEN WHERE TEN_DANG_NHAP = 'binh_vt.hv' ->Ma_lop_hoc = null -> ko co du lieu
*/


/*
select * from thanhvien where ten_dn='thanh_tc'

select * from thoikhoabieu where ma_lop = 9
select * from monhoctkb where ma_tkb = 5


SELECT * FROM THANHVIEN WHERE ID = 434 --TEN_DN = '10SCM2.25'
SELECT * FROM CHITIETTHANHVIEN WHERE TEN_DANG_NHAP = '10SCM2.25' --MA_LOP_HOC = 6
SELECT * FROM THOIKHOABIEU WHERE MA_LOP = 6 --ID = 15,16,17
SELECT * FROM MONHOCTKB WHERE MA_TKB IN (15,16,17)
SELECT * FROM DANGKYMONHOC WHERE MA_HOC_VIEN = 434
SELECT * FROM DANGKYMONHOC WHERE MA_MON_HOC_TKB = 126 AND MA_HOC_VIEN = 434


SELECT * FROM THANHVIEN WHERE ID = 187 --TEN_DN = '10KTHD1.02'
SELECT * FROM CHITIETTHANHVIEN WHERE TEN_DANG_NHAP = '10KTHD1.02' --MA_LOP_HOC = 7
SELECT * FROM THOIKHOABIEU WHERE MA_LOP = 7 --ID = 15,16,17
SELECT * FROM MONHOCTKB WHERE MA_TKB IN (4,7,19)
SELECT * FROM DANGKYMONHOC WHERE MA_HOC_VIEN = 187
SELECT * FROM DANGKYMONHOC WHERE MA_MON_HOC_TKB = 24 AND MA_HOC_VIEN = 187



SELECT * FROM THANHVIEN WHERE TEN_DN = '10SCM2.25'
SELECT * FROM CHITIETTHANHVIEN WHERE TEN_DANG_NHAP = '10SCM2.25'--'10KTHN1.02'
SELECT * FROM THOIKHOABIEU WHERE MA_LOP = 6
SELECT * FROM MONHOCTKB WHERE MA_TKB IN (15,16,17)
SELECT * FROM DANGKYMONHOC WHERE MA_HOC_VIEN = 434 AND MA_MON_HOC_TKB = 11

*/