
INSERT INTO sys_Menu VALUES(1,N'Tờ Trình','images/icon_menu/themcongtac.png','/HungVuongISO/ISO/ToTrinh/ShowToTrinh.jsp','','','','','')
INSERT INTO sys_Role_Menu VALUES(0,45,'','','','','')
INSERT INTO sys_Role_Menu VALUES(1,45,'','','','','')
INSERT INTO sys_Role_Menu VALUES(2,45,'','','','','')
INSERT INTO sys_Role_Menu VALUES(3,45,'','','','','')
INSERT INTO sys_Role_Menu VALUES(4,45,'','','','','')
INSERT INTO sys_Role_Menu VALUES(5,45,'','','','','')
INSERT INTO sys_Role_Menu VALUES(6,45,'','','','','')
INSERT INTO sys_Role_Menu VALUES(7,45,'','','','','')
INSERT INTO sys_Role_Menu VALUES(8,45,'','','','','')
INSERT INTO sys_Role_Menu VALUES(9,45,'','','','','')
INSERT INTO sys_Role_Menu VALUES(10,45,'','','','','')
INSERT INTO sys_Role_Menu VALUES(11,45,'','','','','')
INSERT INTO sys_Role_Menu VALUES(12,45,'','','','','')
INSERT INTO sys_Role_Menu VALUES(13,45,'','','','','')
INSERT INTO sys_Role_Menu VALUES(14,45,'','','','','')
INSERT INTO sys_Role_Menu VALUES(15,45,'','','','','')
INSERT INTO sys_Role_Menu VALUES(16,45,'','','','','')