INSERT INTO sys_Menu VALUES(1,N'Kế Hoạch Tháng','images/icon_menu/themcongtac.png','/HungVuongISO/ISO/KeHoachCongTacThang/ShowKeHoachThang.jsp','','','','','')
INSERT INTO sys_Role_Menu VALUES(0,44,'','','','','')
INSERT INTO sys_Role_Menu VALUES(1,44,'','','','','')
INSERT INTO sys_Role_Menu VALUES(2,44,'','','','','')
INSERT INTO sys_Role_Menu VALUES(3,44,'','','','','')
INSERT INTO sys_Role_Menu VALUES(4,44,'','','','','')
INSERT INTO sys_Role_Menu VALUES(5,44,'','','','','')
INSERT INTO sys_Role_Menu VALUES(6,44,'','','','','')
INSERT INTO sys_Role_Menu VALUES(7,44,'','','','','')
INSERT INTO sys_Role_Menu VALUES(8,44,'','','','','')
INSERT INTO sys_Role_Menu VALUES(9,44,'','','','','')
INSERT INTO sys_Role_Menu VALUES(10,44,'','','','','')
INSERT INTO sys_Role_Menu VALUES(11,44,'','','','','')
INSERT INTO sys_Role_Menu VALUES(12,44,'','','','','')
INSERT INTO sys_Role_Menu VALUES(13,44,'','','','','')
INSERT INTO sys_Role_Menu VALUES(14,44,'','','','','')
INSERT INTO sys_Role_Menu VALUES(15,44,'','','','','')
INSERT INTO sys_Role_Menu VALUES(16,44,'','','','','')