package org.apache.jsp.ISO.ThoiKhoaBieu;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import vn.edu.hungvuongaptech.model.ChiTietMonHocCTDTModel;
import vn.edu.hungvuongaptech.dao.ChiTietMonHocCTDTDAO;
import java.util.ArrayList;
import vn.edu.hungvuongaptech.model.PhongBanModel;
import vn.edu.hungvuongaptech.dao.PhongBanDAO;
import vn.edu.hungvuongaptech.model.DeCuongMonHocModel;
import vn.edu.hungvuongaptech.dao.DeCuongMonHocDAO;
import vn.edu.hungvuongaptech.model.ChiTietThanhVienModel;
import vn.edu.hungvuongaptech.dao.ChiTietTKBDAO;
import vn.edu.hungvuongaptech.dao.ChiTietThanhVienDAO;
import vn.edu.hungvuongaptech.model.NoiDungDCMHModel;
import vn.edu.hungvuongaptech.dao.NoiDungDCMHDAO;
import vn.edu.hungvuongaptech.model.SuDungModel;
import vn.edu.hungvuongaptech.dao.SuDungDAO;
import vn.edu.hungvuongaptech.model.MonHocTKBModel;
import vn.edu.hungvuongaptech.model.ThanhVienModel;
import vn.edu.hungvuongaptech.dao.ThanhVienDAO;
import vn.edu.hungvuongaptech.model.ChiTietTKBModel;

public final class UpdateThoiKhoaBieu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Cập nhật môn học TKB</title>\r\n");
      out.write("<script language=\"JavaScript\" type=\"text/javascript\">\r\n");
      out.write("var tonTai = 0; // kiem tra bang 1 co ton tai khong -0 : chua ton tai -1 : da ton tai\r\n");
      out.write("var obj = window.dialogArguments;\r\n");
      out.write("var addTKB = new Object(); //obj dung de tra ve\r\n");
      out.write("var soThucHanh = 0;\r\n");
      out.write("var soLyThuyet = 0;\r\n");
      out.write("var soTiet = 0;\r\n");
      out.write("var listSuDungPhong;\r\n");
      out.write("var STT = 0, soBuoiTongCong = 0;// STT : so thu tu cua tung buoi trong bang 1, soBuoiTongCong : tong so buoi cua mon hoc\r\n");
      out.write("var tonTaiBang = false; //kiem tra xem bang 2 ton tai chua -true : da ton tai -false : chua ton tai\r\n");
      out.write("var kieu; // mang luu kieu day cua bang theo trinh tu ben de cuong\r\n");
      out.write("var objMonHocTKB = new Object();\r\n");
      out.write("var tuanBatDau = 0;\r\n");

	ArrayList<PhongBanModel> phongBanModelList = PhongBanDAO.getAllPhongBan();
	ArrayList<ThanhVienModel> thanhVienModelList = ThanhVienDAO.getAllGiaoVienOrderByTen();

      out.write("\r\n");
      out.write("function loadPage()\r\n");
      out.write("{\r\n");
      out.write("\tvar param = 0;\r\n");
      out.write("\t");

		out.print("document.getElementById('txtMaTKB').value = '" + request.getParameter("maTKB") + "';");
		out.print("document.getElementById('txtMaMonHocTKB').value = '" + request.getParameter("maMonHocTKB") + "';");
		// code moi sua
		if(request.getAttribute("monHocTKB") != null && request.getParameter("UpdateThanhCong") != null)
		{
			out.print("param = 1;");
			MonHocTKBModel monHocModel = (MonHocTKBModel) request.getAttribute("monHocTKB");
			out.print("addTKB.maMonHocTKB = '" + monHocModel.getMaMonHocTKB() + "';");
			out.print("addTKB.soNoiDung = '" + monHocModel.getSoNoiDung() + "';");
			out.print("addTKB.soCaThucHanh = '" + monHocModel.getSoCaThucHanh() + "';");
			out.print("addTKB.maMonHoc = '" + monHocModel.getMaMonHoc() + "';");
			out.print("addTKB.tenMonHoc = '" + monHocModel.getTenMonHoc() + "';");
			out.print("addTKB.maGiaoVien = '" + monHocModel.getMaGiaoVien() + "';");
			out.print("addTKB.tenGiaoVien = '" + monHocModel.getTenGiaoVien() + "';");
			out.print("addTKB.ghiChu = '" + monHocModel.getGhiChu() + "';");
			if(monHocModel.getTuanBatDauLT().equals(""))
				out.print("addTKB.tuanBatDauLT = '0';");
			else
				out.print("addTKB.tuanBatDauLT = '" + monHocModel.getTuanBatDauLT() + "';");
			if(monHocModel.getTuanBatDauTH().equals(""))
				out.print("addTKB.tuanBatDauTH = '0';");
			else
				out.print("addTKB.tuanBatDauTH = '" + monHocModel.getTuanBatDauTH() + "';");
			
			//out.print("addTKB.tuanKetThucLT = '" + monHocModel.getTuanKetThucLT() + "';");
			//out.print("addTKB.tuanKetThucTH = '" + monHocModel.getTuanKetThucTH() + "';");
			out.print("addTKB.ngayBatDauLT = '" + monHocModel.getNgayBatDauLT().replaceAll("-","/") + "';");
			out.print("addTKB.ngayBatDauTH = '" + monHocModel.getNgayBatDauTH().replaceAll("-","/") + "';");
			out.print("addTKB.ngayKetThucLT = '" + monHocModel.getNgayKetThucLT().replaceAll("-","/") + "';");
			out.print("addTKB.ngayKetThucTH = '" + monHocModel.getNgayKetThucTH().replaceAll("-","/") + "';");
			out.print("addTKB.chuoiThuTrongTuan = '" + monHocModel.getChuoiThuTrongTuan() + "';");
			out.print("addTKB.phongLT= '" + monHocModel.getChuoiPhongLT() + "';");
			out.print("addTKB.phongTH= '" + monHocModel.getChuoiPhongTH() + "';");
			out.print("addTKB.kieuBienSoan = '" + monHocModel.getKieuBienSoan() + "';");
			out.print("addTKB.soTietLT = '" + monHocModel.getLyThuyetCTMH() + "';");
			out.print("addTKB.soTietTH = '" + monHocModel.getThucHanhCTMH() + "';");
			out.print("addTKB.maPhongLT = '" + monHocModel.getUser1() + "';");
			out.print("addTKB.maPhongTH = '" + monHocModel.getUser2() + "';");
			out.print("var chiTietTKBList = new Array();");
			for(int i=0;i<monHocModel.getChiTietTKBModelList().size();i++)
			{
				out.print("var chiTietTKB = new Object();");
				out.print("chiTietTKB.maChiTietTKB = '" + monHocModel.getChiTietTKBModelList().get(i).getMaChiTietTKB() + "';");
				out.print("chiTietTKB.buoi = '" + monHocModel.getChiTietTKBModelList().get(i).getBuoi() + "';");
				out.print("chiTietTKB.sTTNoiDung = '" + monHocModel.getChiTietTKBModelList().get(i).getsTTNoiDung() + "';");
				out.print("chiTietTKB.coHieu = '" + monHocModel.getChiTietTKBModelList().get(i).getCoHieu() + "';");
				out.print("chiTietTKB.hinhThucDay = '" + monHocModel.getChiTietTKBModelList().get(i).getHinhThucDay() + "';");
				out.print("chiTietTKB.thuTrongTuan = '" + monHocModel.getChiTietTKBModelList().get(i).getThuTrongTuan() + "';");
				out.print("chiTietTKB.phong = '" + monHocModel.getChiTietTKBModelList().get(i).getMaPhong() + "';");
				out.print("chiTietTKB.tuan = '" + monHocModel.getChiTietTKBModelList().get(i).getTuan() + "';");
				out.print("chiTietTKB.soThuTu = '" + monHocModel.getChiTietTKBModelList().get(i).getSoThuTu() + "';");
				out.print("chiTietTKB.nhom = '" + monHocModel.getChiTietTKBModelList().get(i).getNhom() + "';");
				out.print("chiTietTKB.tenChuong = '" + monHocModel.getChiTietTKBModelList().get(i).getTenChuong() + "';");
				//out.print("chiTietTKB.maSuDung = '" + monHocModel.getSuDungModelList().get(i).getMaSuDung() + "';");
		
				out.print("chiTietTKBList[chiTietTKBList.length] = chiTietTKB;");
			}
			out.print("addTKB.chiTietTKBList = chiTietTKBList;");
			out.print("if(navigator.appName != 'Netscape') {");
			out.print("var winOpen = window.opener;");
			out.print("winOpen.traVe(addTKB);");
			out.print("winOpen.returnValue = winOpen.addTKB;");
			out.print("winOpen.close(); }");
			out.print("else { ");
			out.print("window.returnValue = addTKB; }");
			out.print("window.close(); ");
		} else if(request.getParameter("Error") != null)
		{
			out.print("param = 1;");
			out.print("alert('Thêm môn học thời khóa biểu không thành công');");
			out.print("window.close();");
		}
		//
	
      out.write("\r\n");
      out.write("\tif(param == 0)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tdocument.getElementById('TableHidden').insertRow(0).insertCell(0).innerHTML = \"\";\r\n");
      out.write("\t\tdocument.getElementById('TableHidden').rows[0].insertCell(1).innerHTML = \"\";\r\n");
      out.write("\t\tdocument.getElementById('TableButton').insertRow(0).insertCell(0).innerHTML = \"\";\r\n");
      out.write("\t\tdocument.getElementById('TongHocSinh').value = obj.soHocSinh;\r\n");
      out.write("\t\tobjMonHocTKB = obj.monHocTKB;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tdocument.getElementById('MangChiTietLength').value = objMonHocTKB.chiTietTKBList.length;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tcreateGiaoVien();\r\n");
      out.write("\t\tcreateTuanLe();\r\n");
      out.write("\t\tcreatePhongBan('phongLyThuyet');\r\n");
      out.write("\t\tcreatePhongBan('phongThucHanh');\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//cap nhat mon hoc tkb\r\n");
      out.write("\t\tdocument.getElementById('txtTenMonHoc').value = objMonHocTKB.tenMonHoc;\r\n");
      out.write("\t\tdocument.getElementById('txtMonHoc').value = objMonHocTKB.maMonHoc; // co the khong can\r\n");
      out.write("\t\tdocument.getElementById('SoNoiDung').value = objMonHocTKB.soNoiDung;\r\n");
      out.write("\t\tdocument.getElementById('txtSoNoiDung').value = objMonHocTKB.soNoiDung;\r\n");
      out.write("\t\tdocument.getElementById('giaoVien').value = objMonHocTKB.maGiaoVien;\r\n");
      out.write("\t\tdocument.getElementById('phongLyThuyet').value = objMonHocTKB.phongLyThuyet; \r\n");
      out.write("\t\tdocument.getElementById('phongThucHanh').value = objMonHocTKB.phongThucHanh; \r\n");
      out.write("\t\tdocument.getElementById('SoCa').value = objMonHocTKB.soCaThucHanh;\r\n");
      out.write("\t\tdocument.getElementById('txtTenGiaoVien').value = objMonHocTKB.tenGiaoVien;\r\n");
      out.write("\t\tdocument.getElementById('GhiChu').value = objMonHocTKB.ghiChu;\r\n");
      out.write("\t\tdocument.getElementById('phongLyThuyet').value = objMonHocTKB.maPhongLT;\r\n");
      out.write("\t\tdocument.getElementById('phongThucHanh').value = objMonHocTKB.maPhongTH;\r\n");
      out.write("\t\tif(objMonHocTKB.maPhongLT == \"null\") {\r\n");
      out.write("\t\t\tdocument.getElementById('phongLyThuyet').options[0].selected = true;\r\n");
      out.write("\t\t\tdocument.getElementById('phongLyThuyet').disabled = true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(objMonHocTKB.maPhongTH == \"null\") {\r\n");
      out.write("\t\t\tdocument.getElementById('phongThucHanh').options[0].selected = true;\r\n");
      out.write("\t\t\tdocument.getElementById('phongThucHanh').disabled = true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif((parseInt(objMonHocTKB.tuanBatDauLT) <= parseInt(objMonHocTKB.tuanBatDauTH) && objMonHocTKB.tuanBatDauLT != 0) || parseInt(objMonHocTKB.tuanBatDauTH) == 0)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tdocument.getElementById('TuanLeBatDau').value = objMonHocTKB.tuanBatDauLT;\r\n");
      out.write("\t\t\ttuanBatDau = parseInt(objMonHocTKB.tuanBatDauLT);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse \r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tdocument.getElementById('TuanLeBatDau').value = objMonHocTKB.tuanBatDauTH;\r\n");
      out.write("\t\t\ttuanBatDau = parseInt(objMonHocTKB.tuanBatDauTH);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tcreateTableKieuDay();\r\n");
      out.write("\t\ttaoBang(1);\r\n");
      out.write("\t\t//taoListSuDungPhong();\r\n");
      out.write("\t//\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("function taoListSuDungPhong()\r\n");
      out.write("{\r\n");
      out.write("\tlistSuDungPhong = new Array();\r\n");
      out.write("\t");

	ArrayList<ChiTietTKBModel> chiTietTKBModel = ChiTietTKBDAO.getAllSuDungPhongByNamHoc(request.getParameter("maNamHoc"),request.getParameter("maMonHocTKB"));
	// tao list su dung phong
		out.print("var thuTuTuan, buoi, thu;");
		out.print("var listPhong = new Array();");
		out.print("var listThu = new Array();");
		out.print("var listBuoi = new Array();");
		for(int i=0;i<chiTietTKBModel.size();i++)
		{
			if(i == chiTietTKBModel.size() - 1)
			{
				out.print("thuTuTuan = '';");
				out.print("buoi = '';");
				out.print("thu = '';");
			}
			else
			{
				out.print("thuTuTuan = '" + chiTietTKBModel.get(i + 1).getTuan() + "';");
				out.print("buoi = '" + chiTietTKBModel.get(i + 1).getBuoi() + "';");
				out.print("thu = '" + chiTietTKBModel.get(i + 1).getThuTrongTuan() + "';");
			}
			out.print("var objPhong = new Object;");
			out.print("objPhong.maPhong = '" + chiTietTKBModel.get(i).getMaPhong() + "';");
			out.print("objPhong.maGiaoVien = '" + chiTietTKBModel.get(i).getMaGiaoVien() + "';");
			out.print("listPhong[listPhong.length] = objPhong;");
			out.print("if(thu != '" + chiTietTKBModel.get(i).getThuTrongTuan() + "' || buoi != '" + chiTietTKBModel.get(i).getBuoi() + "' || thuTuTuan != '" + chiTietTKBModel.get(i).getTuan() + "') {");
				out.print("var objThu = new Object();");
				out.print("objThu.thu = '" + chiTietTKBModel.get(i).getThuTrongTuan() + "';");
				out.print("objThu.listPhong = listPhong;");
				out.print("listThu[listThu.length] = objThu;");
				out.print("var listPhong = new Array();");
			out.print("}");	
			
			out.print("if(buoi != '" + chiTietTKBModel.get(i).getBuoi() + "' || thuTuTuan != '" + chiTietTKBModel.get(i).getTuan() + "') {");
				out.print("var objBuoi = new Object();");
				out.print("objBuoi.buoi = '" + chiTietTKBModel.get(i).getBuoi() + "';");
				out.print("objBuoi.listThu = listThu;");
				out.print("listBuoi[listBuoi.length] = objBuoi;");
				out.print("var listThu = new Array();");
			out.print("}");	
			
			out.print("if(thuTuTuan != '" + chiTietTKBModel.get(i).getTuan() + "') {");
				out.print("var objTuan = new Object();");
				out.print("objTuan.tuan = '" + chiTietTKBModel.get(i).getTuan() + "';");
				out.print("objTuan.listBuoi = listBuoi;");
				out.print("listSuDungPhong[listSuDungPhong.length] = objTuan;");
				out.print("var listBuoi = new Array();");
			out.print("}");
		}
	
      out.write("\r\n");
      out.write("}\r\n");
      out.write("function createTuanLe()\r\n");
      out.write("{\t\r\n");
      out.write("\tfor(var i= parseInt(obj.tuanLe[0]);i<=parseInt(obj.tuanLe[1]);i++)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar opt = new Option(i,i);\r\n");
      out.write("\t\tdocument.getElementById('TuanLeBatDau').add(opt, undefined);\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function createGiaoVien()\r\n");
      out.write("{\r\n");
      out.write("\tdocument.getElementById('giaoVien').innerHTML = null;\r\n");
      out.write("\tvar opt = new Option('Select','');\r\n");
      out.write("\tdocument.getElementById('giaoVien').add(opt,undefined);\r\n");
      out.write("\t");

		for(int i=0;i<thanhVienModelList.size();i++) {
			out.print("var opt = new Option('" + thanhVienModelList.get(i).getHoThanhVien() + " " + thanhVienModelList.get(i).getTenLot() + " " + thanhVienModelList.get(i).getTenThanhVien() + "','" + thanhVienModelList.get(i).getMaThanhVien() + "');");
			out.print("document.getElementById('giaoVien').add(opt,undefined);");
		}
		                                                     
	
      out.write("\r\n");
      out.write("}\r\n");
      out.write("function selectGiaoVien()\r\n");
      out.write("{\r\n");
      out.write("\tdocument.getElementById('txtTenGiaoVien').value = document.getElementById('giaoVien').options[document.getElementById('giaoVien').selectedIndex].text;\r\n");
      out.write("}\r\n");
      out.write("function createPhongBan()\r\n");
      out.write("{\r\n");
      out.write("\tdocument.getElementById('phongLyThuyet').innerHTML = null;\r\n");
      out.write("\tdocument.getElementById('phongThucHanh').innerHTML = null;\r\n");
      out.write("\t");

		for(int i=0;i<phongBanModelList.size();i++) {
			out.print("if('LT' == '" + phongBanModelList.get(i).getChucNang() + "') {");
			out.print("var opt = new Option('" + phongBanModelList.get(i).getKiHieu() + "','" + phongBanModelList.get(i).getMaPhongBan() + "');");
			out.print("document.getElementById('phongLyThuyet').add(opt,undefined); }");
			out.print("if('TH' == '" + phongBanModelList.get(i).getChucNang() + "') {");
			out.print("var opt = new Option('" + phongBanModelList.get(i).getKiHieu() + "','" + phongBanModelList.get(i).getMaPhongBan() + "');");
			out.print("document.getElementById('phongThucHanh').add(opt,undefined); }");
		}
	
      out.write("\r\n");
      out.write("\tselectPhongThucHanh();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function createTableKieuDay()// tao bang 1 de chon thu tu cac buoi hoc ly thuyet va thuc hanh, chi duoc tao ra khi kieu bien soan la 1 voi so LT va TH phai > 0\r\n");
      out.write("{\r\n");
      out.write("\tvar coHieu = \"\", day;\r\n");
      out.write("\tkieu = new Array;\r\n");
      out.write("\tdocument.getElementById('TableHidden').rows[0].cells[0].innerHTML = \"\";\r\n");
      out.write("\tdocument.getElementById('TableHidden').rows[0].cells[1].innerHTML = \"\";\r\n");
      out.write("\tSTT = 0;\r\n");
      out.write("\tvar table = document.getElementById('TableKieuDay');\r\n");
      out.write("\r\n");
      out.write("\tvar temp = \"\"; // dung de so sanh voi so thu tu noi dung\r\n");
      out.write("\tvar arrChiTiet = new Array();\r\n");
      out.write("\tarrChiTiet = objMonHocTKB.chiTietTKBList;\r\n");
      out.write("\t\r\n");
      out.write("\tif(tonTai == 1)\r\n");
      out.write("\t{\r\n");
      out.write("\t\ttable.deleteRow(1);\r\n");
      out.write("\t\ttable.deleteRow(0);\r\n");
      out.write("\t\ttonTai = 0;\r\n");
      out.write("\t}\r\n");
      out.write("\tif(objMonHocTKB.kieuBienSoan == '0' && objMonHocTKB.soTietLT != '0' && objMonHocTKB.soTietTH != '0')\r\n");
      out.write("\t{\r\n");
      out.write("\t\ttonTai = 1;\t\r\n");
      out.write("\t\tvar tr1 = table.insertRow(0);\r\n");
      out.write("\t\tvar tr2 = table.insertRow(1);\r\n");
      out.write("\r\n");
      out.write("\t\tvar hidden = \"\";\r\n");
      out.write("\t\ttr1.insertCell(0).innerHTML = \"STT Nội dung chương\";\r\n");
      out.write("\t\ttr2.insertCell(0).innerHTML = \"\";\r\n");
      out.write("\t\t// cap nhat mon hoc tkb\r\n");
      out.write("\t\tfor(var i=0;i<arrChiTiet.length;i++)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tif(i != 0)\r\n");
      out.write("\t\t\t\ttemp = objChiTiet.sTTNoiDung;\r\n");
      out.write("\t\t\tvar objChiTiet = new Object();\r\n");
      out.write("\t\t\tobjChiTiet = arrChiTiet[i];\r\n");
      out.write("\t\t\tif(objChiTiet.sTTNoiDung != temp)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tSTT++;\r\n");
      out.write("\t\t\t\ttr1.insertCell(STT).innerHTML = STT;\r\n");
      out.write("\t\t\t\tif(objChiTiet.coHieu == 0)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\ttr2.insertCell(STT).innerHTML = \"<input type = 'radio' name = 'KieuDay_\" + STT + \"' id = 'KieuDay_LT\" + STT + \"' value = 'LT' checked = 'checked'>LT</input><br/><input type = 'radio' name = 'KieuDay_\" + STT + \"' id = 'KieuDay_TH\" + STT + \"' value = 'TH'>TH</input>\";\r\n");
      out.write("\t\t\t\t\tsoLyThuyet++;\r\n");
      out.write("\t\t\t\t\tkieu[STT-1] = 'LT-' + objChiTiet.coHieu + '-' + objChiTiet.tenChuong;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse if(objChiTiet.coHieu == 1)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tsoThucHanh++;\r\n");
      out.write("\t\t\t\t\tkieu[STT-1] = 'TH-' + objChiTiet.coHieu + '-' + objChiTiet.tenChuong;\r\n");
      out.write("\t\t\t\t\ttr2.insertCell(STT).innerHTML = \"<input type = 'radio' name = 'KieuDay_\" + STT + \"' id = 'KieuDay_LT\" + STT + \"' value = 'LT' >LT</input><br/><input type = 'radio' name = 'KieuDay_\" + STT + \"' id = 'KieuDay_TH\" + STT + \"' value = 'TH' checked = 'checked'>TH</input>\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse if(objChiTiet.coHieu == 4)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tif(objChiTiet.hinhThucDay == 'LT')\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\ttr2.insertCell(STT).innerHTML = \"<input type = 'radio' name = 'KieuDay_\" + STT + \"' id = 'KieuDay_LT\" + STT + \"' value = 'LT' checked = 'checked' disabled = 'disabled'>LT</input><br/><input type = 'radio' name = 'KieuDay_\" + STT + \"' id = 'KieuDay_TH\" + STT + \"' value = 'TH' disabled = 'disabled'>TH</input>\";\r\n");
      out.write("\t\t\t\t\t\tsoLyThuyet++;\t\r\n");
      out.write("\t\t\t\t\t\tkieu[STT-1] = 'LT-' + objChiTiet.coHieu + '-' + objChiTiet.tenChuong;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\telse\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\ttr2.insertCell(STT).innerHTML = \"<input type = 'radio' name = 'KieuDay_\" + STT + \"' id = 'KieuDay_LT\" + STT + \"' value = 'LT' disabled = 'disabled'>LT</input><br/><input type = 'radio' name = 'KieuDay_\" + STT + \"' id = 'KieuDay_TH\" + STT + \"' value = 'TH' checked = 'checked' disabled = 'disabled'>TH</input>\";\r\n");
      out.write("\t\t\t\t\t\tsoThucHanh++;\r\n");
      out.write("\t\t\t\t\t\tkieu[STT-1] = 'TH-' + objChiTiet.coHieu + '-' + objChiTiet.tenChuong;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\thidden = \"<input type = 'hidden' value = '\" + objChiTiet.sTTNoiDung + \"-\" + objChiTiet.coHieu + \"' name = 'STT_noi_dung\" + STT + \"' id = 'STT_noi_dung\" + STT + \"'/>\";\r\n");
      out.write("\t\t\t\tcoHieu = \"<input type = 'hidden' value = '\" + kieu[STT-1] + \"-\" + STT + \"' name = 'Day\" + STT + \"' id = 'Day\" + STT + \"'/>\";\r\n");
      out.write("\t\t\t\tdocument.getElementById('TableHidden').rows[0].cells[1].innerHTML = document.getElementById('TableHidden').rows[0].cells[1].innerHTML + coHieu;\r\n");
      out.write("\t\t\t\tdocument.getElementById('TableHidden').rows[0].cells[0].innerHTML = document.getElementById('TableHidden').rows[0].cells[0].innerHTML + hidden;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\telse if(objMonHocTKB.kieuBienSoan == '1' || objMonHocTKB.kieuBienSoan == '0')\r\n");
      out.write("\t{\r\n");
      out.write("\t\t//cap nhat mon hoc tkb\r\n");
      out.write("\t\tvar count = 0;\r\n");
      out.write("\t\tfor(var i=0;i<arrChiTiet.length;i++)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tif(i != 0)\r\n");
      out.write("\t\t\t\ttemp = objChiTiet.sTTNoiDung;\r\n");
      out.write("\t\t\tvar objChiTiet = new Object();\r\n");
      out.write("\t\t\tobjChiTiet = arrChiTiet[i];\r\n");
      out.write("\t\t\tif(objChiTiet.sTTNoiDung != temp)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tSTT++;\r\n");
      out.write("\t\t\t\tif(objChiTiet.coHieu == 0)\r\n");
      out.write("\t\t\t\t\tday = 'LT';\r\n");
      out.write("\t\t\t\telse if(objChiTiet.coHieu == 1)\r\n");
      out.write("\t\t\t\t\tday = 'TH';\r\n");
      out.write("\t\t\t\telse if(objChiTiet.coHieu == 4)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tif(objChiTiet.hinhThucDay == 'LT')\r\n");
      out.write("\t\t\t\t\t\tday = 'LT';\r\n");
      out.write("\t\t\t\t\telse\r\n");
      out.write("\t\t\t\t\t\tday = 'TH';\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tcoHieu = \"<input type = 'hidden' value = '\" + day + \"-\" + STT + \"-\" + objChiTiet.coHieu + \"-\" + objChiTiet.tenChuong + \"' name = 'Day\" + STT + \"' id = 'Day\" + STT + \"'/>\";\r\n");
      out.write("\t\t\t\thidden = \"<input type = 'hidden' value = '\" + objChiTiet.sTTNoiDung + \"' name = 'STT_noi_dung\" + STT + \"' id = 'STT_noi_dung\" + STT + \"'/>\";\r\n");
      out.write("\t\t\t\tdocument.getElementById('TableHidden').rows[0].cells[1].innerHTML = document.getElementById('TableHidden').rows[0].cells[1].innerHTML + coHieu;\r\n");
      out.write("\t\t\t\tdocument.getElementById('TableHidden').rows[0].cells[0].innerHTML = document.getElementById('TableHidden').rows[0].cells[0].innerHTML + hidden;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tif(objMonHocTKB.kieuBienSoan == '1')\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tcount++;\r\n");
      out.write("\t\t\t\t\tif(count == parseInt(document.getElementById('SoCa').value))\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tSTT++;\r\n");
      out.write("\t\t\t\t\t\tcount = 0;\r\n");
      out.write("\t\t\t\t\t\tday = 'TH';\r\n");
      out.write("\t\t\t\t\t\tcoHieu = \"<input type = 'hidden' value = '\" + day + \"-\" + STT + \"-\" + objChiTiet.coHieu + \"-\" + objChiTiet.tenChuong + \"' name = 'Day\" + STT + \"' id = 'Day\" + STT + \"'/>\";\r\n");
      out.write("\t\t\t\t\t\thidden = \"<input type = 'hidden' value = '\" + objChiTiet.sTTNoiDung + \"' name = 'STT_noi_dung\" + STT + \"' id = 'STT_noi_dung\" + STT + \"'/>\";\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById('TableHidden').rows[0].cells[1].innerHTML = document.getElementById('TableHidden').rows[0].cells[1].innerHTML + coHieu;\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById('TableHidden').rows[0].cells[0].innerHTML = document.getElementById('TableHidden').rows[0].cells[0].innerHTML + hidden;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\telse\r\n");
      out.write("\t{\r\n");
      out.write("\t\tfor(var i=0;i<arrChiTiet.length;i++)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tif(i != 0)\r\n");
      out.write("\t\t\t\ttemp = objChiTiet.sTTNoiDung;\r\n");
      out.write("\t\t\tvar objChiTiet = new Object();\r\n");
      out.write("\t\t\tobjChiTiet = arrChiTiet[i];\r\n");
      out.write("\t\t\tif(objChiTiet.sTTNoiDung != temp)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tSTT++;\r\n");
      out.write("\t\t\t\tday = \"THP\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tcoHieu = \"<input type = 'hidden' value = '\" + day + \"-\" + STT + \"-\" + objChiTiet.coHieu + \"-\" + objChiTiet.tenChuong + \"' name = 'Day\" + STT + \"' id = 'Day\" + STT + \"'/>\";\r\n");
      out.write("\t\t\thidden = \"<input type = 'hidden' value = '\" + STT + \"' name = 'STT_noi_dung\" + STT + \"' id = 'STT_noi_dung\" + STT + \"'/>\";\r\n");
      out.write("\t\t\tdocument.getElementById('TableHidden').rows[0].cells[1].innerHTML = document.getElementById('TableHidden').rows[0].cells[1].innerHTML + coHieu;\r\n");
      out.write("\t\t\tdocument.getElementById('TableHidden').rows[0].cells[0].innerHTML = document.getElementById('TableHidden').rows[0].cells[0].innerHTML + hidden;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tcreateButton();\r\n");
      out.write("}\r\n");
      out.write("function createButton()// tao ra 2 button tao bang va xoa bang\r\n");
      out.write("{\r\n");
      out.write("\tdocument.getElementById('TableButton').rows[0].cells[0].innerHTML = \"<input type = 'button' value = 'Tạo bảng' id = 'TaoBang' onclick = 'taoBang(0)'/> <input type = 'button' value = 'Xóa bảng' id = 'XoaBang' onclick = 'xoaBang()' disabled = 'disabled'/>\";\r\n");
      out.write("}\r\n");
      out.write("function taoBang(x)\r\n");
      out.write("{\r\n");
      out.write("\tvar kiemTraSoBuoi = true;\r\n");
      out.write("\tif(document.getElementById('TuanLeBatDau').value != '')\r\n");
      out.write("\t{\r\n");
      out.write("\t\tif(objMonHocTKB.kieuBienSoan == '0' && objMonHocTKB.soTietLT != '0' && objMonHocTKB.soTietTH != '0')\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tkiemTraSoBuoi = kiemTraKieuDay();\r\n");
      out.write("\t\t\tif(kiemTraSoBuoi)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tfor(var i=1;i<=STT;i++)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tdocument.getElementById('KieuDay_LT' + i).disabled = true;\r\n");
      out.write("\t\t\t\t\tdocument.getElementById('KieuDay_TH' + i).disabled = true;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(kiemTraSoBuoi)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tif(x == 0)\r\n");
      out.write("\t\t\t\tselectKieuDay('1',0);\r\n");
      out.write("\t\t\telse\r\n");
      out.write("\t\t\t\tselectKieuDay('1',1);\r\n");
      out.write("\t\t\tdocument.getElementById('TaoBang').disabled = true;\r\n");
      out.write("\t\t\tdocument.getElementById('SoNoiDung').disabled = true;\r\n");
      out.write("\t\t\tdocument.getElementById('SoCa').readOnly = true;\r\n");
      out.write("\t\t\tdocument.getElementById('XoaBang').disabled = false;\r\n");
      out.write("\t\t\tdocument.getElementById('TuanLeBatDau').disabled = true;\r\n");
      out.write("\t\t\ttonTaiBang = true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t\talert(\"Số buổi học lý thuyết và thực hành không đúng\");\t\r\n");
      out.write("\t}\r\n");
      out.write("\telse\r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"Hãy chọn tuần bắt đầu\");\r\n");
      out.write("\t}\t\r\n");
      out.write("}\r\n");
      out.write("function xoaBang()\r\n");
      out.write("{\r\n");
      out.write("\tselectKieuDay('0');\r\n");
      out.write("\tdocument.getElementById('TaoBang').disabled = false;\r\n");
      out.write("\tdocument.getElementById('SoNoiDung').disabled = false;\r\n");
      out.write("\tdocument.getElementById('SoCa').readOnly = false;\r\n");
      out.write("\tdocument.getElementById('XoaBang').disabled = true;\r\n");
      out.write("\tsoBuoiTongCong = 0;\r\n");
      out.write("\tdocument.getElementById('TuanLeBatDau').disabled = false;\r\n");
      out.write("\tif(objMonHocTKB.kieuBienSoan == '0' && objMonHocTKB.soTietLT != '0' && objMonHocTKB.soTietTH != '0')\r\n");
      out.write("\t{\r\n");
      out.write("\t\tfor(var i=1;i<=STT;i++)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tdocument.getElementById('KieuDay_LT' + i).disabled = false;\r\n");
      out.write("\t\t\tdocument.getElementById('KieuDay_TH' + i).disabled = false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\ttonTaiBang = false;\r\n");
      out.write("}\r\n");
      out.write("function kiemTraKieuDay() // kiem tra lai trinh tu hoc o bang 1 va sap xep lai cho dung\r\n");
      out.write("{\r\n");
      out.write("\tvar demLT = 0, demTH = 0;\r\n");
      out.write("\tvar soBuoiLT = 0;\r\n");
      out.write("\tvar soBuoiTH = 0;\r\n");
      out.write("\tfor(var i=1;i<=STT;i++){\r\n");
      out.write("\t\tif(document.getElementById('KieuDay_LT' + i).checked == true)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tfor(var j=demLT;j<kieu.length;j++)\r\n");
      out.write("\t\t\t{\t\r\n");
      out.write("\t\t\t\tif((kieu[j].split(\"-\"))[0] == 'LT')\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tdocument.getElementById('STT_noi_dung' + i).value = j+1;\r\n");
      out.write("\t\t\t\t\tdemLT = j + 1;\r\n");
      out.write("\t\t\t\t\tdocument.getElementById('Day' + i).value = 'LT-' + i + '-' + (kieu[j].split(\"-\"))[1] + '-' + (kieu[j].split(\"-\"))[2];\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tsoBuoiLT++;\r\n");
      out.write("\t\t}\t\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tfor(var j=demTH;j<kieu.length;j++)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tif((kieu[j].split(\"-\"))[0] == 'TH')\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tdocument.getElementById('STT_noi_dung' + i).value = j+1;\r\n");
      out.write("\t\t\t\t\tdemTH = j + 1;\r\n");
      out.write("\t\t\t\t\tdocument.getElementById('Day' + i).value = 'TH-' + i + '-' + (kieu[j].split(\"-\"))[1] + '-' + (kieu[j].split(\"-\"))[2];\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tsoBuoiTH++;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tif(soBuoiLT == soLyThuyet && soBuoiTH == soThucHanh)\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\telse\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("}\r\n");
      out.write("function selectSoNoiDung()\r\n");
      out.write("{\r\n");
      out.write("\tdocument.getElementById('txtSoNoiDung').value = document.getElementById('SoNoiDung').value;\r\n");
      out.write("}\r\n");
      out.write("function selectKieuDay(act, up) // tao bang 2\r\n");
      out.write("{\r\n");
      out.write("\tif(objMonHocTKB.kieuBienSoan == '0' && objMonHocTKB.soTietLT != '0' && objMonHocTKB.soTietTH != '0')\r\n");
      out.write("\t{\r\n");
      out.write("\t\tkiemTraKieuDay();\r\n");
      out.write("\t}\r\n");
      out.write("\tvar table = document.getElementById('TableBuoiHoc');\r\n");
      out.write("\tvar tr;\r\n");
      out.write("\tvar size;\r\n");
      out.write("\tvar x = 1;\r\n");
      out.write("\tvar soTuan = 0;\r\n");
      out.write("\tvar kieuDay, ch;//ch = cờ hiệu\r\n");
      out.write("\tvar y;\r\n");
      out.write("\tvar soNoiDung;\r\n");
      out.write("\tvar disable;\r\n");
      out.write("\tvar option = \"\";\r\n");
      out.write("\tvar dem = 1;\r\n");
      out.write("\tvar hiddenTuan;\r\n");
      out.write("\tvar so = -1;\r\n");
      out.write("\tvar phongBan = \"\";\r\n");
      out.write("\tvar soBuoiMoiTuan = 0;\r\n");
      out.write("\tvar selectThu = \"\";\r\n");
      out.write("\tvar selectNhom = \"\";\r\n");
      out.write("\tvar chonPhong = \"\";\r\n");
      out.write("\tvar tenChuong = \"\";\r\n");
      out.write("\tvar hiddenTenChuong;\r\n");
      out.write("\tvar selectNhomHoc = \"\";\r\n");
      out.write("\tvar selectBuoiHoc = \"\";\r\n");
      out.write("\tif(act == '0')\r\n");
      out.write("\t{\r\n");
      out.write("\t\tfor(var i = soBuoiTongCong;i>=0;i--)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\ttable.deleteRow(i);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\telse\r\n");
      out.write("\t{\r\n");
      out.write("\t\t\r\n");
      out.write("\t\ttable.insertRow(0);\r\n");
      out.write("\t\ttable.rows[0].insertCell(0).innerHTML = \"Số Tuần\";\r\n");
      out.write("\t\ttable.rows[0].insertCell(1).innerHTML = \"Số Buổi\";\r\n");
      out.write("\t\ttable.rows[0].insertCell(2).innerHTML = \"Buổi\";\r\n");
      out.write("\t\ttable.rows[0].insertCell(3).innerHTML = \"Kiểu dạy\";\r\n");
      out.write("\t\ttable.rows[0].insertCell(4).innerHTML = \"Nhóm\";\r\n");
      out.write("\t\ttable.rows[0].insertCell(5).innerHTML = \"Thứ\";\r\n");
      out.write("\t\ttable.rows[0].insertCell(6).innerHTML = \"Phòng\";\r\n");
      out.write("\t\tfor(var i=1;i<=parseInt(document.getElementById('SoCa').value);i++)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\toption += \"<option value = '\" + i + \"'>\" + i + \"</option>\";\r\n");
      out.write("\t\t}   \r\n");
      out.write("\t\tfor(var i=1;i<=STT;i++)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tif((document.getElementById('Day' + i).value.split(\"-\")[0]) == 'LT')\r\n");
      out.write("\t\t\t\tsoBuoiMoiTuan++;\r\n");
      out.write("\t\t\telse\r\n");
      out.write("\t\t\t\tfor(var n=1;n<=parseInt(document.getElementById('SoCa').value);n++)\r\n");
      out.write("\t\t\t\t\tsoBuoiMoiTuan++;\r\n");
      out.write("\t\t\tso = -1; \r\n");
      out.write("\t\t\tif(objMonHocTKB.kieuBienSoan == '1')\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tif(i%((parseInt(objMonHocTKB.soTietTH) + parseInt(objMonHocTKB.soTietLT))/parseInt(objMonHocTKB.soTietLT)) == 0)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tso = 0;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tso = 0;\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif((parseInt((document.getElementById('Day' + i).value.split(\"-\"))[1])%parseInt(document.getElementById('txtSoNoiDung').value) == 0 && so == 0) || i == STT)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tselectThu = \"\";\r\n");
      out.write("\t\t\t\tselectNhomHoc = \"\";\r\n");
      out.write("\t\t\t\tselectBuoiHoc = \"\";\r\n");
      out.write("\t\t\t\tsoTuan++;\r\n");
      out.write("\t\t\t\tif(soTuan == 1)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tselectThu = \"onchange = 'selectThuTrongTuan()'\";\r\n");
      out.write("\t\t\t\t\tselectNhomHoc = \"onchange = 'selectNhom()'\";\r\n");
      out.write("\t\t\t\t\tselectBuoiHoc = \"onclick = 'selectBuoi()'\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tfor(var j=x;j<=i;j++)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tdem = 1;\r\n");
      out.write("\t\t\t\t\tsoNoiDung = document.getElementById('STT_noi_dung' + j).value;\r\n");
      out.write("\t\t\t\t\ttr = table.insertRow(soBuoiTongCong + 1);\r\n");
      out.write("\t\t\t\t\tif(j == x)\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\ttr.insertCell(0).innerHTML = (soTuan + tuanBatDau - 1);\r\n");
      out.write("\t\t\t\t\t\ttable.rows[soBuoiTongCong + 1].cells[0].rowSpan = soBuoiMoiTuan;\r\n");
      out.write("\t\t\t\t\t\tdem = 0;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tif((document.getElementById('Day' + j).value.split(\"-\")[0]) == 'LT')\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tkieuDay = \"LT\";\r\n");
      out.write("\t\t\t\t\t\tch = document.getElementById('Day' + j).value.split(\"-\")[2];\r\n");
      out.write("\t\t\t\t\t\ttenChuong = document.getElementById('Day' + j).value.split(\"-\")[3];\r\n");
      out.write("\t\t\t\t\t\ty = 1;\r\n");
      out.write("\t\t\t\t\t\tdisable = \"disabled = 'disabled'\";\r\n");
      out.write("\t\t\t\t\t\tphongBan = document.getElementById('phongLyThuyet').innerHTML;\r\n");
      out.write("\t\t\t\t\t\tchonPhong = document.getElementById('phongLyThuyet').value;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\telse\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tkieuDay = document.getElementById('Day' + j).value.split(\"-\")[0];;\r\n");
      out.write("\t\t\t\t\t\tch = document.getElementById('Day' + j).value.split(\"-\")[2];\r\n");
      out.write("\t\t\t\t\t\ttenChuong = document.getElementById('Day' + j).value.split(\"-\")[3];\r\n");
      out.write("\t\t\t\t\t\ty = parseInt(document.getElementById('SoCa').value);\r\n");
      out.write("\t\t\t\t\t\tdisable = \"\";\r\n");
      out.write("\t\t\t\t\t\tphongBan = document.getElementById('phongThucHanh').innerHTML;\r\n");
      out.write("\t\t\t\t\t\tchonPhong = document.getElementById('phongThucHanh').value;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tfor(var z = 1;z<=y;z++)\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tsoBuoiTongCong++;\r\n");
      out.write("\t\t\t\t\t\tif(z != 1)\r\n");
      out.write("\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\ttr = table.insertRow(soBuoiTongCong);\r\n");
      out.write("\t\t\t\t\t\t\tdem = 1;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\ttr.insertCell(1-dem).innerHTML = soBuoiTongCong;\r\n");
      out.write("\t\t\t\t\t\ttr.insertCell(2-dem).innerHTML = \"<input type = 'radio' name = 'Buoi\" + soBuoiTongCong + \"' id = 'BuoiSang\" + soBuoiTongCong + \"' value = 'Sáng-\" + soNoiDung + \"-\" + ch + \"' checked='checked' \" + selectBuoiHoc + \"/>Sáng<input type = 'radio' name = 'Buoi\" + soBuoiTongCong + \"' id = 'BuoiChieu\" + soBuoiTongCong + \"' value = 'Chiều-\" + soNoiDung + \"-\" + ch + \"' \" + selectBuoiHoc + \"/>Chiều\";\r\n");
      out.write("\t\t\t\t\t\ttr.insertCell(3-dem).innerHTML = \"<input type = 'text' name = 'HinhThucDay\" + soBuoiTongCong + \"' value = '\" + kieuDay + \"' id = 'HinhThucDay\" + soBuoiTongCong + \"' readonly = 'readonly'/>\";\r\n");
      out.write("\t\t\t\t\t\ttr.insertCell(4-dem).innerHTML = \"<select name = 'Nhom\" + soBuoiTongCong + \"' id = 'Nhom\" + soBuoiTongCong + \"' \" + selectNhom + disable + selectNhomHoc + \">\" + option + \"</select>\";\r\n");
      out.write("\t\t\t\t\t\ttr.insertCell(5-dem).innerHTML = \"<select name = 'Thu\" + soBuoiTongCong + \"' id = 'Thu\" + soBuoiTongCong + \"' \" + selectThu + \"><option value = '1'>Thứ hai</option><option value = '2'>Thứ ba</option><option value = '3'>Thứ tư</option><option value = '4'>Thứ năm</option><option value = '5'>Thứ sáu</option><option value = '6'>Thứ bảy</option><option value = '7'>Chủ nhật</option></select>\";\r\n");
      out.write("\t\t\t\t\t\ttr.insertCell(6-dem).innerHTML = \"<select id = 'Phong\" + soBuoiTongCong + \"' name = 'Phong\" + soBuoiTongCong + \"'>\" + phongBan + \"</select><font color = 'red'></font>\";\r\n");
      out.write("\t\t\t\t\t\ttr.cells[6-dem].id = \"tdPhong\" + soBuoiTongCong;\r\n");
      out.write("\t\t\t\t\t\t//hiddenBuoi = \"<input type = 'hidden' name = 'hiddenBuoi\" + soBuoiTongCong + \"' value = '\" + soBuoiTongCong + \"'/>\";\r\n");
      out.write("\t\t\t\t\t\thiddenTuan = \"<input type = 'hidden' name = 'hiddenTuan\" + soBuoiTongCong   + \"' value = '\" + (soTuan + tuanBatDau - 1) + \"' id = 'hiddenTuan\" + soBuoiTongCong + \"'/>\";\r\n");
      out.write("\t\t\t\t\t\thiddenTenChuong = \"<input type = 'hidden' name = 'hiddenTenChuong\" + soBuoiTongCong   + \"' value = '\" + tenChuong + \"' id = 'hiddenTenChuong\" + soBuoiTongCong + \"'/>\";\r\n");
      out.write("\t\t\t\t\t\ttable.rows[soBuoiTongCong].cells[0].innerHTML = table.rows[soBuoiTongCong].cells[0].innerHTML + hiddenTuan + hiddenTenChuong;\t\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById('Phong' + soBuoiTongCong).value = chonPhong;\t\r\n");
      out.write("\t\t\t\t\t\tif(up == 1)\r\n");
      out.write("\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\tvar objChiTiet = new Object();\r\n");
      out.write("\t\t\t\t\t\t\tobjChiTiet = objMonHocTKB.chiTietTKBList[soBuoiTongCong-1];\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('ChuoiMaChiTietTKB').value += objChiTiet.maChiTietTKB + \"<->\";\r\n");
      out.write("\t\t\t\t\t\t\tif(objChiTiet.buoi == 'Sáng')\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('BuoiSang' + soBuoiTongCong).checked = true;\r\n");
      out.write("\t\t\t\t\t\t\telse\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('BuoiChieu' + soBuoiTongCong).checked = true;\r\n");
      out.write("\t\t\t\t\t\t\t//document.getElementById('HinhThucDay' + soBuoiTongCong).value = objChiTiet.hinhThucDay;\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('Nhom' + soBuoiTongCong).value = objChiTiet.nhom;\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('Thu' + soBuoiTongCong).value = objChiTiet.thuTrongTuan;\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('Phong' + soBuoiTongCong).value = objChiTiet.phong;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tx = i + 1;\r\n");
      out.write("\t\t\t\tsoBuoiMoiTuan = 0;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("function changeMonHoc()\r\n");
      out.write("{\r\n");
      out.write("\tdocument.getElementById('txtMonHoc').value = document.getElementById('monHoc').value;\r\n");
      out.write("\tdocument.getElementById('txtTenMonHoc').value = document.getElementById('monHoc').options[document.getElementById('monHoc').selectedIndex].text;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function changeTuanBatDau()\r\n");
      out.write("{\r\n");
      out.write("\ttuanBatDau = parseInt(document.getElementById('TuanLeBatDau').value);\r\n");
      out.write("}\r\n");
      out.write("function changePhongLyThuyet()\r\n");
      out.write("{\r\n");
      out.write("\tfor(var i=1;i<=soBuoiTongCong;i++)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tif(document.getElementById('HinhThucDay' + i).value == 'LT')\r\n");
      out.write("\t\t\tdocument.getElementById('Phong' + i).value = document.getElementById('phongLyThuyet').value;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("function changePhongThucHanh()\r\n");
      out.write("{\r\n");
      out.write("\tfor(var i=1;i<=soBuoiTongCong;i++)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tif(document.getElementById('HinhThucDay' + i).value != 'TH' || document.getElementById('HinhThucDay' + i).value != 'THP')\r\n");
      out.write("\t\t\tdocument.getElementById('Phong' + i).value = document.getElementById('phongThucHanh').value;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("function kiemTraTrungGioHoc()\r\n");
      out.write("{\r\n");
      out.write("\tvar check = true, tinhTrang = true;\r\n");
      out.write("\tvar tuan = \"na\";\r\n");
      out.write("\tvar temp;\r\n");
      out.write("\tfor(var i=1;i<=soBuoiTongCong;i++)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar phong = document.getElementById('Phong' + i).value;\r\n");
      out.write("\t\tvar tdPhong = document.getElementById('tdPhong' + i).innerHTML;\r\n");
      out.write("\t\tvar c = tdPhong.charAt(tdPhong.length-8);\r\n");
      out.write("\t\ttinhTrang = true;\r\n");
      out.write("\t\tif(c != \">\") {\r\n");
      out.write("\t\t\ttdPhong = tdPhong.replace(\">\" + c + \"</font>\",\"></font>\");\r\n");
      out.write("\t\t\ttdPhong = tdPhong.replace(\">\" + c + \"</FONT>\",\"></FONT>\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(document.getElementById('hiddenTuan' + i).value != tuan)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\ttuan = document.getElementById('hiddenTuan' + i).value;\r\n");
      out.write("\t\t\ttemp = i;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tfor(var j=temp;j<i;j++)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tvar phong1 = document.getElementById('Phong' + j).value;\r\n");
      out.write("\t\t\t\tvar tdPhong1 = document.getElementById('tdPhong' + j).innerHTML;\r\n");
      out.write("\t\t\t\tvar c1 = tdPhong1.charAt(tdPhong1.length-8);\r\n");
      out.write("\t\t\t\tif(document.getElementById('BuoiSang' + i).checked == document.getElementById('BuoiSang' + j).checked && document.getElementById('BuoiChieu' + i).checked == document.getElementById('BuoiChieu' + j).checked)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tif(document.getElementById('Thu' + i).value == document.getElementById('Thu' + j).value)\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tif(c1 != \">\" && c1 != \"#\") {\r\n");
      out.write("\t\t\t\t\t\t\ttdPhong1 = tdPhong1.replace(\">\" + c1 + \"</font>\",\">#</font>\");\r\n");
      out.write("\t\t\t\t\t\t\ttdPhong1 = tdPhong1.replace(\">\" + c1 + \"</FONT>\",\">#</FONT>\");\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\telse {\r\n");
      out.write("\t\t\t\t\t\t\ttdPhong1 = tdPhong1.replace(\"></font>\",\">#</font>\");\r\n");
      out.write("\t\t\t\t\t\t\ttdPhong1 = tdPhong1.replace(\"></FONT>\",\">#</FONT>\");\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById('tdPhong' + j).innerHTML = tdPhong1;\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById('Phong' + j).value = phong1;\r\n");
      out.write("\t\t\t\t\t\tcheck = false;\r\n");
      out.write("\t\t\t\t\t\ttinhTrang = false;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(tinhTrang == false)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tif(c != \">\" && c != \"#\") { \r\n");
      out.write("\t\t\t\t\ttdPhong = tdPhong.replace(\">\" + c + \"</font>\",\">#</font>\");\r\n");
      out.write("\t\t\t\t\ttdPhong = tdPhong.replace(\">\" + c + \"</FONT>\",\">#</FONT>\");alert(tdPhong);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse {\r\n");
      out.write("\t\t\t\t\ttdPhong = tdPhong.replace(\"></font>\",\">#</font>\");\r\n");
      out.write("\t\t\t\t\ttdPhong = tdPhong.replace(\"></FONT>\",\">#</FONT>\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tdocument.getElementById('tdPhong' + i).innerHTML = tdPhong;\r\n");
      out.write("\t\tdocument.getElementById('Phong' + i).value = phong;\r\n");
      out.write("\t}\r\n");
      out.write("\treturn check;\r\n");
      out.write("}\r\n");
      out.write("function selectThuTrongTuan() // chon thu trong dong dau tien thi thu o cac dong sau se chay theo\r\n");
      out.write("{\r\n");
      out.write("\tvar thuTuTuan = tuanBatDau - 1;\r\n");
      out.write("\tvar demSoNgay = 1;\r\n");
      out.write("\tfor(var i=1;i<=soBuoiTongCong;i++)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tif(parseInt(document.getElementById('hiddenTuan' + i).value) != thuTuTuan)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tthuTuTuan = parseInt(document.getElementById('hiddenTuan' + i).value);\r\n");
      out.write("\t\t\tdemSoNgay = 1;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(thuTuTuan > tuanBatDau - 1)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tdocument.getElementById('Thu' + i).value = document.getElementById('Thu' + demSoNgay).value;\r\n");
      out.write("\t\t\tdemSoNgay++;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("function selectNhom() // chon nhom trong dong dau tien thi nhom o cac dong sau se chay theo\r\n");
      out.write("{\r\n");
      out.write("\tvar thuTuTuan = tuanBatDau - 1;\r\n");
      out.write("\tvar demSoNgay = 1;\r\n");
      out.write("\tfor(var i=1;i<=soBuoiTongCong;i++)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tif(parseInt(document.getElementById('hiddenTuan' + i).value) != thuTuTuan)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tthuTuTuan = parseInt(document.getElementById('hiddenTuan' + i).value);\r\n");
      out.write("\t\t\tdemSoNgay = 1;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(thuTuTuan > tuanBatDau - 1)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tdocument.getElementById('Nhom' + i).value = document.getElementById('Nhom' + demSoNgay).value;\r\n");
      out.write("\t\t\tdemSoNgay++;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("function selectBuoi() // chon nhom trong dong dau tien thi nhom o cac dong sau se chay theo\r\n");
      out.write("{\r\n");
      out.write("\tvar thuTuTuan = tuanBatDau - 1;\r\n");
      out.write("\tvar demSoNgay = 1;\r\n");
      out.write("\tfor(var i=1;i<=soBuoiTongCong;i++)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tif(parseInt(document.getElementById('hiddenTuan' + i).value) != thuTuTuan)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tthuTuTuan = parseInt(document.getElementById('hiddenTuan' + i).value);\r\n");
      out.write("\t\t\tdemSoNgay = 1;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(thuTuTuan > tuanBatDau - 1)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tdocument.getElementById('BuoiSang' + i).checked = document.getElementById('BuoiSang' + demSoNgay).checked;\r\n");
      out.write("\t\t\tdocument.getElementById('BuoiChieu' + i).checked = document.getElementById('BuoiChieu' + demSoNgay).checked;\r\n");
      out.write("\t\t\tdemSoNgay++;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("function taoMonHoc()// tao ra mon hoc voi day du du lieu va truyen ve cu so chinh\r\n");
      out.write("{\r\n");
      out.write("\tvar check = true, checkBuoi = true, err = false;\r\n");
      out.write("\tvar table = document.getElementById('TableBuoiHoc');\r\n");
      out.write("\tdocument.getElementById('txtSoBuoi').value = soBuoiTongCong;\r\n");
      out.write("\tdocument.getElementById('MaNamHoc').value = ");
      out.print(request.getParameter("maNamHoc"));
      out.write(";\r\n");
      out.write("\t//alert(document.getElementById('MaNamHoc').value);\r\n");
      out.write("\tif(document.getElementById('txtMonHoc').value == \"\")\r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"Hãy chọn môn học\");\r\n");
      out.write("\t\tcheck = false;\r\n");
      out.write("\t}\r\n");
      out.write("\telse if(document.getElementById('giaoVien').value == \"\")\r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"Hãy chọn giáo viên\");\r\n");
      out.write("\t\tcheck = false;\r\n");
      out.write("\t} \r\n");
      out.write("\telse if(tonTaiBang == false)\r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"Hãy tạo bảng trước\");\r\n");
      out.write("\t\tcheck = false;\r\n");
      out.write("\t}\r\n");
      out.write("\telse if(kiemTraTrungGioHoc() == false)\r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"Giờ học không hợp lệ\");\r\n");
      out.write("\t\tcheck = false;\r\n");
      out.write("\t}\r\n");
      out.write("\telse \r\n");
      out.write("\t{\r\n");
      out.write("\t\ttaoListSuDungPhong();\r\n");
      out.write("\t\tvar buoi = '';\r\n");
      out.write("\t\tfor(var i=1;i<=soBuoiTongCong;i++)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tvar phong = document.getElementById('Phong' + i).value;\r\n");
      out.write("\t\t\tif(document.getElementById('BuoiSang' + i).checked == true)\r\n");
      out.write("\t\t\t\tbuoi = 'Sáng';\r\n");
      out.write("\t\t\telse\r\n");
      out.write("\t\t\t\tbuoi = 'Chiều';\t\t\r\n");
      out.write("\t\t\tfor(var j=0;j<listSuDungPhong.length;j++)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tvar objTuan = new Object();\r\n");
      out.write("\t\t\t\tobjTuan = listSuDungPhong[j];\r\n");
      out.write("\t\t\t\tif(document.getElementById('hiddenTuan' + i).value == objTuan.tuan)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tvar listBuoi = new Array();\r\n");
      out.write("\t\t\t\t\tlistBuoi = objTuan.listBuoi;\r\n");
      out.write("\t\t\t\t\tfor(var k =0;k<listBuoi.length;k++)\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tvar objBuoi = new Object();\r\n");
      out.write("\t\t\t\t\t\tobjBuoi = listBuoi[k];\r\n");
      out.write("\t\t\t\t\t\tif(buoi == objBuoi.buoi)\r\n");
      out.write("\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\tvar listThu = new Array();\r\n");
      out.write("\t\t\t\t\t\t\tlistThu = objBuoi.listThu;\r\n");
      out.write("\t\t\t\t\t\t\tfor(var h =0;h<listThu.length;h++)\r\n");
      out.write("\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\tvar objThu = new Object();\r\n");
      out.write("\t\t\t\t\t\t\t\tobjThu = listThu[h];\r\n");
      out.write("\t\t\t\t\t\t\t\tif(document.getElementById('Thu' + i).value == objThu.thu)\r\n");
      out.write("\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar listPhong = new Array();\r\n");
      out.write("\t\t\t\t\t\t\t\t\tlistPhong = objThu.listPhong;\r\n");
      out.write("\t\t\t\t\t\t\t\t\tfor(var m=0;m<listPhong.length;m++)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvar objPhong = new Object();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tobjPhong = listPhong[m];\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvar tdPhong = document.getElementById('tdPhong' + i).innerHTML;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvar c = tdPhong.charAt(tdPhong.length-8);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tif(document.getElementById('Phong' + i).value == objPhong.maPhong)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tif(c != \">\" && c != \"*\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\ttdPhong = tdPhong.replace(\">\" + c + \"</font>\", \">*</font>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\ttdPhong = tdPhong.replace(\">\" + c + \"</FONT>\", \">*</FONT>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\telse \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\ttdPhong = tdPhong.replace(\"></font>\", \">*</font>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\ttdPhong = tdPhong.replace(\"></FONT>\", \">*</FONT>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdocument.getElementById('tdPhong' + i).innerHTML = tdPhong;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdocument.getElementById('Phong' + i).value = phong;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\terr = true;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tcheck = false;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\telse if(document.getElementById('giaoVien').value == objPhong.maGiaoVien) \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tif(c != \">\" && c != \"x\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\ttdPhong = tdPhong.replace(\">\" + c + \"</font>\", \">x</font>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\ttdPhong = tdPhong.replace(\">\" + c + \"</FONT>\", \">x</FONT>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\telse \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\ttdPhong = tdPhong.replace(\"></font>\", \">x</font>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\ttdPhong = tdPhong.replace(\"></FONT>\", \">x</FONT>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdocument.getElementById('tdPhong' + i).innerHTML = tdPhong;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdocument.getElementById('Phong' + i).value = phong;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\terr = true;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tcheck = false;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\telse\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tif(c != \">\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\ttdPhong = tdPhong.replace(\">\" + c + \"</font>\", \"></font>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\ttdPhong = tdPhong.replace(\">\" + c + \"</FONT>\", \"></FONT>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdocument.getElementById('tdPhong' + i).innerHTML = tdPhong;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdocument.getElementById('Phong' + i).value = phong;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tif(check == false)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tif(err == true) \r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\talert(\"* : Phòng bị trùng\\nx : Giáo viên bị trùng\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\telse {\r\n");
      out.write("\t\t//changePhongLyThuyet();\r\n");
      out.write("\t\t//changePhongThucHanh();\r\n");
      out.write("\t\tif(confirm(\"Bạn có chắc muốn cập nhật môn học này không ???\"))\r\n");
      out.write("\t\t\ttaoChuoiThuTrongTuan();\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function selectPhongThucHanh()\r\n");
      out.write("{\r\n");
      out.write("\t");

		for(int i=0;i<phongBanModelList.size();i++) {
			out.print("if(document.getElementById('phongThucHanh').value == '" + phongBanModelList.get(i).getMaPhongBan() + "')");
			out.print("document.getElementById('SucChua').value = '" + phongBanModelList.get(i).getSucChua() + "';");
		}
	
      out.write("\r\n");
      out.write("}\r\n");
      out.write("function taoChuoiThuTrongTuan() // tao 1 chuoi de display ben cua so chinh va gan cac gia tri vao obj addTKB\r\n");
      out.write("{\r\n");
      out.write("\tvar chuoiPhongTH = \"\";\r\n");
      out.write("\tvar chuoiPhongLT = \"\";\r\n");
      out.write("\tvar chuoi = \"\";\r\n");
      out.write("\tvar chuoiThuTrongTuan = \"\";\r\n");
      out.write("\tvar str = \"\";\r\n");
      out.write("\tvar soTuanLT = 0, soTuanTH = 0;\r\n");
      out.write("\t\r\n");
      out.write("\taddTKB.tuanKetThucLT = \"\";\r\n");
      out.write("\taddTKB.tuanKetThucTH = \"\";\r\n");
      out.write("\taddTKB.tuanBatDauLT = \"\";\r\n");
      out.write("\taddTKB.tuanBatDauTH = \"\";\r\n");
      out.write("\t\r\n");
      out.write("\tfor(var i=1;i<=soBuoiTongCong;i++)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tif(document.getElementById('HinhThucDay' + i).value == 'LT') {\r\n");
      out.write("\t\t\tsoTuanLT++;\r\n");
      out.write("\t\t\taddTKB.tuanKetThucLT = document.getElementById('hiddenTuan' + i).value;\r\n");
      out.write("\t\t\t// code phần phòng\r\n");
      out.write("\t\t\tif(chuoiPhongLT.match(document.getElementById('Phong' + i).options[document.getElementById('Phong' + i).selectedIndex].text) == null)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tif(chuoiPhongLT == \"\")\r\n");
      out.write("\t\t\t\t\tchuoiPhongLT += document.getElementById('Phong' + i).options[document.getElementById('Phong' + i).selectedIndex].text;\r\n");
      out.write("\t\t\t\telse\r\n");
      out.write("\t\t\t\t\tchuoiPhongLT += \"-\" + document.getElementById('Phong' + i).options[document.getElementById('Phong' + i).selectedIndex].text;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t//\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse // su dung cho TH va Tich hop\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tsoTuanTH++;\r\n");
      out.write("\t\t\taddTKB.tuanKetThucTH = document.getElementById('hiddenTuan' + i).value;\r\n");
      out.write("\t\t\t// code phần phòng\r\n");
      out.write("\t\t\tif(chuoiPhongTH.match(document.getElementById('Phong' + i).options[document.getElementById('Phong' + i).selectedIndex].text) == null)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tif(chuoiPhongTH == \"\")\r\n");
      out.write("\t\t\t\t\tchuoiPhongTH += document.getElementById('Phong' + i).options[document.getElementById('Phong' + i).selectedIndex].text;\r\n");
      out.write("\t\t\t\telse\r\n");
      out.write("\t\t\t\t\tchuoiPhongTH += \"-\" + document.getElementById('Phong' + i).options[document.getElementById('Phong' + i).selectedIndex].text;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t//\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(soTuanLT == 1)\r\n");
      out.write("\t\t\taddTKB.tuanBatDauLT = addTKB.tuanKetThucLT;\r\n");
      out.write("\t\tif(soTuanTH == 1)\r\n");
      out.write("\t\t\taddTKB.tuanBatDauTH = addTKB.tuanKetThucTH;\r\n");
      out.write("\t\tif(i == 1)\r\n");
      out.write("\t\t\tstr = \"\";\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t\tstr = \"-\";\r\n");
      out.write("\t\tif(document.getElementById('BuoiSang' + i).checked == true)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tchuoi += 'Sáng/' + document.getElementById('Thu' + i).value + '/' + document.getElementById('HinhThucDay' + i).value;\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tchuoi += 'Chiều/' + document.getElementById('Thu' + i).value + '/' + document.getElementById('HinhThucDay' + i).value;\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(!chuoiThuTrongTuan.match(chuoi))\r\n");
      out.write("\t\t\tchuoiThuTrongTuan += str + chuoi;\r\n");
      out.write("\t\tchuoi = \"\";\r\n");
      out.write("\t}\r\n");
      out.write("\tdocument.getElementById('Tuan_bat_dau_LT').value = addTKB.tuanBatDauLT;\r\n");
      out.write("\tdocument.getElementById('Tuan_bat_dau_TH').value = addTKB.tuanBatDauTH;\r\n");
      out.write("\tdocument.getElementById('Tuan_ket_thuc_LT').value = addTKB.tuanKetThucLT;\r\n");
      out.write("\tdocument.getElementById('Tuan_ket_thuc_TH').value = addTKB.tuanKetThucTH;\r\n");
      out.write("\tdocument.getElementById('ChuoiThuTrongTuan').value = chuoiThuTrongTuan;\r\n");
      out.write("\tdocument.getElementById('ChuoiPhongLT').value = chuoiPhongLT;\r\n");
      out.write("\tdocument.getElementById('ChuoiPhongTH').value = chuoiPhongTH;\r\n");
      out.write("\tdocument.getElementById('KieuBienSoan').value = objMonHocTKB.kieuBienSoan;\r\n");
      out.write("\tdocument.getElementById('SoTietLyThuyet').value = objMonHocTKB.soTietLT;\r\n");
      out.write("\tdocument.getElementById('SoTietThucHanh').value = objMonHocTKB.soTietTH;\r\n");
      out.write("\t\r\n");
      out.write("\tdocument.forms[\"AddThoiKhoaBieu\"].submit();\r\n");
      out.write("}\r\n");
      out.write("function closeWindow()\r\n");
      out.write("{\r\n");
      out.write("\twindow.close();\r\n");
      out.write("}\r\n");
      out.write("function traVe(tempObject)\r\n");
      out.write("{\r\n");
      out.write("\taddTKB.maMonHocTKB = tempObject.maMonHocTKB;\r\n");
      out.write("\taddTKB.soNoiDung = tempObject.soNoiDung;\r\n");
      out.write("\taddTKB.soCaThucHanh = tempObject.soCaThucHanh;\r\n");
      out.write("\taddTKB.maMonHoc = tempObject.maMonHoc;\r\n");
      out.write("\taddTKB.tenMonHoc = tempObject.tenMonHoc;\r\n");
      out.write("\taddTKB.maGiaoVien = tempObject.maGiaoVien;\r\n");
      out.write("\taddTKB.tenGiaoVien = tempObject.tenGiaoVien;\r\n");
      out.write("\taddTKB.ghiChu = tempObject.ghiChu;\r\n");
      out.write("\taddTKB.tuanBatDauLT = tempObject.tuanBatDauLT;\r\n");
      out.write("\taddTKB.tuanBatDauTH = tempObject.tuanBatDauTH;\r\n");
      out.write("\taddTKB.ngayBatDauLT = tempObject.ngayBatDauLT;\r\n");
      out.write("\taddTKB.ngayBatDauTH = tempObject.ngayBatDauTH;\r\n");
      out.write("\taddTKB.ngayKetThucLT = tempObject.ngayKetThucLT;\r\n");
      out.write("\taddTKB.ngayKetThucTH = tempObject.ngayKetThucTH;\r\n");
      out.write("\taddTKB.chuoiThuTrongTuan = tempObject.chuoiThuTrongTuan;\r\n");
      out.write("\taddTKB.phongLT= tempObject.phongLT;\r\n");
      out.write("\taddTKB.phongTH= tempObject.phongTH;\r\n");
      out.write("\taddTKB.kieuBienSoan = tempObject.kieuBienSoan;\r\n");
      out.write("\taddTKB.soTietLT = tempObject.soTietLT;\r\n");
      out.write("\taddTKB.soTietTH = tempObject.soTietTH;\r\n");
      out.write("\taddTKB.maPhongLT = tempObject.maPhongLT;\r\n");
      out.write("\taddTKB.maPhongTH = tempObject.maPhongTH;\r\n");
      out.write("\taddTKB.chiTietTKBList = new Array();\r\n");
      out.write("\tvar arr = tempObject.chiTietTKBList;\r\n");
      out.write("\taddTKB.chiTietTKBList = new Array();\r\n");
      out.write("\tfor(var i=0;i<arr.length;i++) {\r\n");
      out.write("\t\taddTKB.chiTietTKBList[i] = new Object();\r\n");
      out.write("\t\taddTKB.chiTietTKBList[i].maChiTietTKB = arr[i].maChiTietTKB;\r\n");
      out.write("\t\taddTKB.chiTietTKBList[i].buoi = arr[i].buoi;\r\n");
      out.write("\t\taddTKB.chiTietTKBList[i].sTTNoiDung = arr[i].sTTNoiDung;\r\n");
      out.write("\t\taddTKB.chiTietTKBList[i].coHieu = arr[i].coHieu;\r\n");
      out.write("\t\taddTKB.chiTietTKBList[i].hinhThucDay = arr[i].hinhThucDay;\r\n");
      out.write("\t\taddTKB.chiTietTKBList[i].thuTrongTuan = arr[i].thuTrongTuan;\r\n");
      out.write("\t\taddTKB.chiTietTKBList[i].phong = arr[i].phong;\r\n");
      out.write("\t\taddTKB.chiTietTKBList[i].tuan = arr[i].tuan;\r\n");
      out.write("\t\taddTKB.chiTietTKBList[i].soThuTu = arr[i].soThuTu;\r\n");
      out.write("\t\taddTKB.chiTietTKBList[i].nhom = arr[i].nhom;\r\n");
      out.write("\t\taddTKB.chiTietTKBList[i].tenChuong = arr[i].tenChuong;\r\n");
      out.write("\t}\t\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body onload=\"loadPage();\">\r\n");
      out.write("\t<form action = \"");
      out.print(request.getContextPath());
      out.write("/thoiKhoaBieuController?themChiTiet=yes\" method=\"post\" name = \"AddThoiKhoaBieu\">\r\n");
      out.write("\t\t<table id = \"TKB\">\r\n");
      out.write("\t\t\t<th colspan=\"4\">Thêm Môn Học</th>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Tổng số học sinh :</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" readonly=\"readonly\" name = \"txtTongHocSinh\" id = \"TongHocSinh\"/></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<td>Tên môn học :</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<input type = \"hidden\" name = \"txtMonHoc\" id = \"txtMonHoc\"/>\r\n");
      out.write("\t\t\t\t\t<input type = \"text\" id = \"txtTenMonHoc\" name = \"txtTenMonHoc\"/>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr id=\"trGiangDay\">\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Giáo viên :</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t<input type = \"hidden\" name=\"txtTenGiaoVien\" id = \"txtTenGiaoVien\"/> \r\n");
      out.write("\t\t\t\t<select id=\"giaoVien\" name=\"cboGiaoVien\" onchange=\"selectGiaoVien();\">\r\n");
      out.write("\t\t\t\t\t<option value=\"\">select</option>\r\n");
      out.write("\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Số nội dung học trong tuần</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<input type = \"hidden\" id = \"txtSoNoiDung\" value = \"1\" name = \"txtSoNoiDung\"/> \r\n");
      out.write("\t\t\t\t\t<select id=\"SoNoiDung\" onchange=\"selectSoNoiDung();\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">1</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2\">2</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"3\">3</option>\r\n");
      out.write("\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t \t<tr>\r\n");
      out.write("\t\t\t\t<td>Phòng học lý thuyết :</td>\r\n");
      out.write("\t\t\t\t<td><select id=\"phongLyThuyet\" onchange=\"changePhongLyThuyet();\" name = \"cboPhongLT\">\r\n");
      out.write("\t\t\t\t\t<option></option>\r\n");
      out.write("\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Phòng học thưc hành :</td>\r\n");
      out.write("\t\t\t\t<td><select id=\"phongThucHanh\" onchange=\"changePhongThucHanh();\" name = \"cboPhongTH\">\r\n");
      out.write("\t\t\t\t\t<option></option>\r\n");
      out.write("\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t<td>Sức chứa :</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" readonly=\"readonly\" id=\"SucChua\"/></td>\r\n");
      out.write("\t\t\t</tr> \r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Số ca thực hành :</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" id = \"SoCa\" value=\"1\" name=\"SoCa\"/></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Tuần bắt đầu :</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<select id = \"TuanLeBatDau\" name=\"cboTuanLeBatDau\" onchange=\"changeTuanBatDau();\">\r\n");
      out.write("\t\t\t\t\t<option value=\"0\">Select</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<table id = \"TableHidden\"></table>\r\n");
      out.write("\t\t<table border=\"1\" id = \"TableKieuDay\"></table>\r\n");
      out.write("\t\t<table id = \"TableButton\"></table>\r\n");
      out.write("\t\t<table border=\"1\" id = \"TableBuoiHoc\"></table>\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t\t<tr><td>Ghi chú\r\n");
      out.write("\t\t\t\t\t<textarea rows=\"5\" cols=\"50\" name = \"areaGhiChu\" id = \"GhiChu\"></textarea>\r\n");
      out.write("\t\t\t</td></tr>\r\n");
      out.write("\t\t");
      //  c:set
      org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /ISO/ThoiKhoaBieu/UpdateThoiKhoaBieu.jsp(1161,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("TinhTrang");
      // /ISO/ThoiKhoaBieu/UpdateThoiKhoaBieu.jsp(1161,2) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(request.getParameter("capNhat"));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
        return;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      out.write("\r\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\t\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<input type=\"hidden\" name = \"txtMaMonHocTKB\" id = \"txtMaMonHocTKB\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" name = \"txtSoBuoi\" id = \"txtSoBuoi\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" name = \"action\" value = \"Update\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" name = \"txtMaTKB\" id = \"txtMaTKB\" value = \"\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" name = \"Tuan_bat_dau_LT\" id = \"Tuan_bat_dau_LT\" value = \"\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" name = \"Tuan_ket_thuc_LT\" id = \"Tuan_ket_thuc_LT\" value = \"\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" name = \"Tuan_bat_dau_TH\" id = \"Tuan_bat_dau_TH\" value = \"\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" name = \"Tuan_ket_thuc_TH\" id = \"Tuan_ket_thuc_TH\" value = \"\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" name = \"MaNamHoc\" id = \"MaNamHoc\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" name = \"ChuoiPhongLT\" id = \"ChuoiPhongLT\" value = \"\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" name = \"ChuoiPhongTH\" id = \"ChuoiPhongTH\" value = \"\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" name = \"ChuoiThuTrongTuan\" id = \"ChuoiThuTrongTuan\" value = \"\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" name = \"KieuBienSoan\" id = \"KieuBienSoan\" value=\"\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" name = \"SoTietLyThuyet\" id = \"SoTietLyThuyet\" value=\"\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" name = \"SoTietThucHanh\" id = \"SoTietThucHanh\" value=\"\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" name = \"ChuoiMaChiTietTKB\" id = \"ChuoiMaChiTietTKB\" value=\"\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" name = \"MangChiTietLength\" id = \"MangChiTietLength\" value=\"\"/>\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(PageContext _jspx_page_context)
          throws Throwable {
    PageContext pageContext = _jspx_page_context;
    JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /ISO/ThoiKhoaBieu/UpdateThoiKhoaBieu.jsp(1162,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${TinhTrang eq 'CapNhat'}", java.lang.Boolean.class, (PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t<tr align=\"center\"><td>\t\r\n");
        out.write("\t\t\t\t<input type=\"button\" value = \"Câp nhật\" onclick=\"taoMonHoc();\"/>\r\n");
        out.write("\t\t\t\t<input type=\"button\" value = \"Cancel\" onclick=\"closeWindow();\"/>\r\n");
        out.write("\t\t\t</td></tr>\t\r\n");
        out.write("\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }
}
